### ISSUE TITLE
Не отображается изображение

### ISSUE THREAD

**Issue by VladSerdobintsev** [PoryvaevAM/freepoker#1]
Для того, чтобы воспроизвести данный баг необходимо:
1. Запустить приложение.
2. Посмотреть в верхнюю веб-приложения.

_Ожидаемый результат_: изображение отображается.
_Фактический результат_: изображение не отображается.

**Comment by PoryvaevAM** [comment]
Исправил! 
Выложил картинку на файлообменнике и указал ссылку вместо локального пути, и все заработало!
