### ISSUE TITLE
Невозможно перейти на страницу FAQ

### ISSUE THREAD

**Issue by VladSerdobintsev** [PoryvaevAM/freepoker#2]
Для воспроизведения данного бага необходимо:
1. Запустить веб-приложение.
2. Залогиниться.
3. Нажать на ссылку меню "FAQ".

_Ожидаемый результат_: будет произведён удачный переход на страницу сайта под названием **FAQ**.
_Фактический результат_: при нажатии на ссылку меню, которая ведёт на страницу **FAQ**, происходит ошибка с номером 404.

**Comment by PoryvaevAM** [comment]
Исправил ошибку, теперь все работает! Исправленную версию закоммитил.
