### ISSUE TITLE
Нет проверки на корректность ведённого email при регистрации

### ISSUE THREAD

**Issue by VladSerdobintsev** [PoryvaevAM/freepoker#3]
Для воспроизведения данного бага необходимо:
1. Запустить веб-приложение.
2. Перейти на страницу регистрации.
3. Заполнить все поля.
4. Поле ввода email адреса заполнить не корректным значением.

_Ожидаемый результат_: выскочит сообщение об ошибке.
_Реальный результат_: производится добавление в базу данных пользователя с некорректным email адресом.

**Comment by PoryvaevAM** [comment]
Создал и подключил файл с  java script кодом, который решает проблему.
