### ISSUE TITLE
Нет проверки на соответствие паролей

### ISSUE THREAD

**Issue by VladSerdobintsev** [PoryvaevAM/freepoker#4]
Для воспроизведения данного бага необходимо:
1. Запустить веб-приложение.
2. Перейти на страницу регистрации.
3. Заполнить все поля.
4. Поле ввода пароля заполнить одним набором символов, а поле ввода "повторить пароль" заполнить другим набором символов.

_Ожидаемый результат_: выскочит сообщение об ошибке.
_Реальный результат_: производится добавление в базу данных пользователя без проверки на соответствие двух вышеуказанных полей.

**Comment by PoryvaevAM** [comment]
Создал и подключил файл с java script кодом, который решает проблему.
