### ISSUE TITLE
Нет проверки на то, все ли поля заполнены

### ISSUE THREAD

**Issue by VladSerdobintsev** [PoryvaevAM/freepoker#5]
Для воспроизведения данного бага необходимо:
1. Запустить веб-приложение.
2. Перейти на страницу регистрации.
3. Нажать кнопку "Registration".

_Ожидаемый результат_: выскочит сообщение об ошибке.
_Реальный результат_: производится добавление в базу данных пользователя без каких-либо данных о нём.

**Comment by PoryvaevAM** [comment]
Создал и подключил файл с java script кодом, который решает проблему.
